name: Post Videos to Facebook

on:
  schedule:
    - cron: "0 12 * * *"  # runs every day at 12:00 UTC
  workflow_dispatch:      # allows manual run

permissions:
  contents: write   # allow workflow to push changes back to the repo

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create service account file
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Run main script
        env:
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
        run: python main.py

      - name: Commit updated posted_cache.json
        if: always()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add posted_cache.json
          git commit -m "Update posted_cache.json [skip ci]" || echo "No changes to commit"
          git push
