name: Post Videos to Facebook Daily

on:
  schedule:
    - cron: '0 8 * * *'  # Runs every day at 08:00 UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  post-video:
    runs-on: ubuntu-latest
    env:
      FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
      FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
      GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON_B64 }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib requests

      - name: Decode Google Service Account
        run: |
          echo "${GOOGLE_SERVICE_ACCOUNT_JSON}" | base64 --decode > service_account.json

      - name: Ensure posted_cache.json exists
        run: |
          if [ ! -f posted_cache.json ]; then
            echo '{"posted_ids": []}' > posted_cache.json
          fi

      - name: Run main.py
        run: python main.py

      - name: Commit updated posted_cache.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add posted_cache.json
          git commit -m "Update posted_cache.json after posting video" || echo "No changes to commit"
          git push
