jobs:
  post-video:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Restore cache
      - name: Restore posted cache
        uses: actions/cache@v3
        id: cache-posted
        with:
          path: posted_cache.json
          key: posted-cache-v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install --upgrade google-api-python-client requests

      - name: Post video
        env:
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: python main.py

      # Save updated cache
      - name: Save posted cache
        uses: actions/cache@v3
        with:
          path: posted_cache.json
          key: posted-cache-v1
