name: Post Videos to Facebook

on:
  schedule:
    - cron: "0 10 * * *"  # daily at 10:00 UTC
  workflow_dispatch:       # manual trigger

jobs:
  post:
    runs-on: ubuntu-latest
    concurrency:
      group: post-videos
      cancel-in-progress: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Restore Google Service Account JSON
        run: |
          mkdir -p $HOME/.secrets
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" | base64 -d > $HOME/.secrets/credentials.json

      - name: Switch to video-cache branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin video-cache
          git checkout video-cache

      - name: Run video poster bot
        env:
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        run: python main.py

      - name: Commit updated posted_cache.json
        run: |
          git add posted_cache.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update posted index"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} video-cache
          fi
