name: Post Videos to Facebook

on:
  schedule:
    - cron: "0 12 * * *"   # once a day at 12:00 UTC
  workflow_dispatch:       # allow manual trigger

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run posting script
        env:
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          set -e
          echo "▶️ Running main.py..."
          python3 main.py || echo "⚠️ Script skipped (already posted today)."

      - name: Commit updated cache
        if: success() || failure()  # always run so cache is saved
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Add only if cache file actually changed
          if git diff --quiet --exit-code posted_cache.json; then
            echo "✅ No cache changes, skipping commit."
          else
            git add posted_cache.json
            git commit -m "Update posted_cache.json [skip ci]" || echo "⚠️ Nothing to commit"
            git push
          fi
