name: Post Videos to Facebook

on:
  schedule:
    - cron: "0 10 * * *"  # daily at 10:00 UTC
  workflow_dispatch:       # manual trigger

permissions:
  contents: write   # allow pushing to repo

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Restore Google Service Account JSON
        run: |
          mkdir -p $HOME/.secrets
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" | base64 -d > $HOME/.secrets/credentials.json
          cat $HOME/.secrets/credentials.json | jq . # sanity check

      - name: Run video poster bot
        env:
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        run: python main.py

      - name: Commit updated cache to video-cache
        run: |
          set -euo pipefail

          # Save the updated cache to a temp file
          TMP_CACHE="$(mktemp)"
          cp posted_cache.json "$TMP_CACHE"

          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"

          git fetch origin video-cache || true
          if git show-ref --verify --quiet refs/remotes/origin/video-cache; then
            # Reset local changes and switch to video-cache
            git reset --hard
            git checkout -B video-cache origin/video-cache
          else
            git checkout --orphan video-cache
            git rm -rf . >/dev/null 2>&1 || true
          fi

          # Restore updated cache
          cp "$TMP_CACHE" posted_cache.json
          rm -f "$TMP_CACHE"

          git add posted_cache.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update posted index"
            git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:video-cache
          fi
