name: Post Videos to Facebook

on:
  schedule:
    - cron: "0 10 * * *"  # daily at 10:00 UTC
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      # ----------------- Checkout -----------------
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0  # full history needed for branch checkout

      # ----------------- Python Setup -----------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ----------------- Google Service Account -----------------
      - name: Restore Google Service Account JSON
        run: |
          mkdir -p $HOME/.secrets
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" | base64 -d > $HOME/.secrets/credentials.json

      # ----------------- Run Video Poster -----------------
      - name: Run video poster bot
        env:
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        run: python main.py

      # ----------------- Commit Cache -----------------
      - name: Commit cache to video-cache branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          # ensure latest remote refs
          git fetch origin || true

          # If remote video-cache exists, check it out and reset to remote version.
          if git ls-remote --exit-code --heads origin video-cache; then
            git checkout video-cache
            git reset --hard origin/video-cache
          else
            # create a local branch from current default branch (checked out by actions/checkout)
            git checkout -b video-cache
          fi

          # ensure posted_cache.json from workspace is staged
          git add posted_cache.json

          # commit only if there are changes
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update posted index"
            git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:video-cache
          fi
