name: Post Videos to Facebook

# Grant write permissions to allow updating posted_cache.json
permissions:
  contents: write

on:
  schedule:
    - cron: "0 8 * * *" # Runs every day at 08:00 UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  post_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth facebook-sdk

      - name: Decode GOOGLE_SERVICE_ACCOUNT_JSON
        if: ${{ env.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "${{ env.GOOGLE_SERVICE_ACCOUNT_JSON }}" | base64 --decode > service_account.json

      - name: Post next video to Facebook
        env:
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          python main.py

      - name: Commit updated posted_cache.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add posted_cache.json
          git commit -m "Update posted_cache.json" || echo "No changes to commit"
          git push
