name: Post Videos to Facebook

on:
  schedule:
    - cron: "0 10 * * *"  # daily at 10:00 UTC
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt google-api-python-client google-auth-httplib2 google-auth-oauthlib requests

      - name: Restore Google Service Account JSON
        run: |
          mkdir -p $HOME/.secrets
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" | base64 -d > $HOME/.secrets/credentials.json

      - name: Run video poster bot
        env:
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        run: python main.py

      - name: Commit cache (posted index)
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          # Switch to video-cache branch
          git fetch origin video-cache
          git checkout video-cache

          # Copy updated posted_cache.json into branch workspace
          cp -f posted_cache.json . || true
          git add posted_cache.json

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update posted index"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:video-cache
          fi
